add template search module and update inference module with it
ostis-apps/ostis-inference pull request #13
Opened 2021-07-01 16:46 UTC by NikiforovSergei

2021-07-03 23:40 UTC, KovalM requested changes

2021-07-03 23:40 UTC, KovalM commented on kb/link_test.scs
> +	@link0 = [Драсте];;
Use English

2021-07-03 23:40 UTC, KovalM commented on problem-solver/cxx/CMakeLists.txt
> +add_subdirectory(templateSearchModule)
Let's discuss about templateSearchModule. I propose not creating separate module for it

2021-07-03 23:40 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +    templateSearchModule::TemplateSearcher templateSearchManager(ms_context);
```suggestion
    templateSearchModule::TemplateSearcher templateSearcher(ms_context);
```

2021-07-03 23:40 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +    templateSearchModule::TemplateSearcher templateSearchManager(ms_context);
Can we create TemplateSearcher in the constructor?

2021-07-03 23:40 UTC, KovalM commented on problem-solver/cxx/templateSearchModule/searcher/TemplateSearcher.cpp
> +      searchResult = searchTemplateWithContent(searchTemplate, templateAddr);
Why we can't pass template params?

2021-07-03 23:40 UTC, KovalM commented on problem-solver/cxx/templateSearchModule/searcher/TemplateSearcher.cpp
> +ScTemplateSearchResultItem TemplateSearcher::getSearchResultItem(const ScTemplateSearchResult & searchResult, const int & itemIndex)
Why we need create new SearchResultItem?

2021-07-05 07:33 UTC, NikiforovSergei commented on problem-solver/cxx/templateSearchModule/searcher/TemplateSearcher.cpp
> +ScTemplateSearchResultItem TemplateSearcher::getSearchResultItem(const ScTemplateSearchResult & searchResult, const int & itemIndex)
this is an unused method. forgot to delete

2021-07-05 12:29 UTC, KovalM commented on problem-solver/cxx/inferenceModule/InferenceModule.hpp
> +  SC_CLASS(LoadOrder(100))
Why we need 100?

2021-07-05 12:32 UTC, KovalM approved these changes

2021-07-05 13:00 UTC, merged