Поддержка комплексных логических формул в части посылки импликативных правил
ostis-apps/ostis-inference pull request #22
Opened 2021-12-09 00:17 UTC by wcobalt

https://github.com/ostis-apps/ostis-inference/issues/18
https://github.com/ostis-apps/ostis-inference/issues/17
https://github.com/ostis-apps/ostis-inference/issues/16

2021-12-09 11:54 UTC, NikitaZotov requested changes
Seperate review fixes commits into commits about logics and refactoring.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
Better to describe these fields in the base class. Class hierarchy doesn't satisfy the DRY principle in programming. Think about it.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +                           ScMemoryContext* context);
Needed "inference::TemplateSearcher * templateSearcher". The asterisk is separated at the sides by spaces in most OSTIS systems. Review everywhere.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    ScTemplateSearchResultItem templateSearchResult{nullptr, nullptr};
2-spaces indent is needed.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    ScMemoryContext* context;
Use unqie_ptr for ScMemoryContext

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    LogicExpressionNode& GetRoot() {
Also for references

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    const std::vector<ScTemplateParams>& GetParamsSet() const {
Const specifier after type

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +};
Add blank row.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    vector<ScAddr> argumentList;
Use ScAddrVector instead of vector of ScAddr

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +    SC_LOG_INFO("Trying to use rule: " + ms_context->HelperGetSystemIdtf(rule));
Why does it log info? Review everywhere.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +        SC_LOG_INFO("Success?: " + std::to_string(success));
Improve this log by ternary logic operator.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +                        string varName = ms_context->HelperGetSystemIdtf(var);
Use std::string instead of using namespace std;

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +                for (auto var : varList)
It is better to write auto const & var : varList

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    if (result.result) {
Rename variable "result"

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +        result2 = rightOp->check(params);
Rename variable "result2"

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    bool tsr2 = result2.hasTemplateSearchResult;
Rename variables. It is not comfortable to read code.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    return res;
Put this code in a separate method. It is repeatable.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    SC_LOG_INFO(context->HelperGetSystemIdtf(templateToCheck) + ": "
Change debug level and etc.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +LogicExpressionResult AndExpressionNode::check(ScTemplateParams params) const {
Wrap the curly brace to the next line and etc.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    SC_LOG_INFO(context->HelperGetSystemIdtf(templateToCheck) + ": "
Improve this log.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +            ScType::Unknown);
Why unknown type is used here?

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +            ScType::Unknown);
Don't create iterators if is is not needed.

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +        SC_LOG_INFO(context->HelperGetSystemIdtf(node) + " is a template")
Use debug level log

2021-12-09 11:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +}
Add blank row

2021-12-09 11:55 UTC, NikitaZotov commented
Add tests to check work of this enhancement.

2021-12-09 11:56 UTC, NikitaZotov commented
And write in preamble of PR how does it work this functionality

2021-12-09 13:48 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    ScMemoryContext* context;
@NikitaZotov unique_ptr предполагает владение ресурсом. Здесь речь о владении не идет

2021-12-09 13:49 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
нет не беттер

2021-12-09 13:53 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
No need to create new classes, you need to add these fields to the base.

2021-12-09 13:56 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
@NikitaZotov тем более глупость учитывая что операторы могут быть не только бинарными

2021-12-09 13:57 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
Add these fields to the base class

> @NikitaZotov плодить классы из-за пары повторяющихся строк - частое желание начинающих программистов, но надо не только знать когда использовать принципы, но и когда их не использовать

2021-12-09 13:59 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
> @NikitaZotov тем более глупость учитывая что операторы могут быть не только бинарными

Read square and rectangle problem.

2021-12-09 13:59 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
операторы могут быть не только бинарными, я не буду добавлять два операнда в базовый класс и даже вектор не буду потому что у ноды может не быть операндов вообще

> Add these fields to the base class
> 
> > @NikitaZotov плодить классы из-за пары повторяющихся строк - частое желание начинающих программистов, но надо не только знать когда использовать принципы, но и когда их не использовать

2021-12-09 14:01 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
It is no needed to create vector of operands.

2021-12-09 14:04 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
> > @NikitaZotov тем более глупость учитывая что операторы могут быть не только бинарными
> 
> Read square and rectangle problem.

о чем ты, полиморфизм на поля не распространяется

2021-12-09 14:05 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
резюмирую: мои унарные операторы не будут содержать два операнда

2021-12-09 14:06 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
Make fields protected in base class and use these in child classes

2021-12-09 14:07 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
> It is no needed to create vector of operands.

добавь t в конце no и a перед vector, а то читать больно

2021-12-09 14:09 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
@KovalM

2021-12-09 14:10 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
Don't be rude to me

2021-12-09 14:12 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.h
> +    std::unique_ptr<LogicExpressionNode> rightOp;
I am not

2021-12-09 14:23 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +            ScType::Unknown);
> Why unknown type is used here?

потому что 2м элементом может быть темплейт, а может быть и кружок с минусом

2021-12-09 14:27 UTC, wcobalt commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +            ScType::Unknown);
![image](https://user-images.githubusercontent.com/24494830/145414629-b714199f-03a3-4c98-be29-2cc35627bbc8.png)

2021-12-15 13:50 UTC, NikitaZotov requested changes

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +    ScAddr& templateItself,
Check it, please.

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +  res.result = !areThereFalse;
Why in "res" variable does "result" field exist? May be it is better to rename variable or field?

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +        ScType::Unknown);
Otherwise, I might think that these are some elements.

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/LogicExpressionChecker.cpp
> +      throw std::runtime_error("[INFERENCE_MODULE] Not operator doesn't have any arguments");
So please improve it and make it look more concise.

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/testStructures/LogicModule/inferenceLogicTrueComplexRuleTest.scs
> +    -> rrel_1: {inference_logic_test_rule};;
Please, add blank row.

2021-12-15 13:50 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/testStructures/LogicModule/inferenceLogicTrueComplexRuleTest.scs
> +    -> rrel_1: {inference_logic_test_rule};;
Correct spacing in brackets.

2022-01-09 17:53 UTC, NikitaZotov approved these changes

2022-01-09 17:54 UTC, merged