[refactor] Changes required for web-platform 0.7.0
ostis-apps/ostis-inference pull request #27
Opened 2022-08-02 13:11 UTC by FallenChromium

This system doesn't compile with the latest version of `sc-machine` due to the breaking changes introduces in the version 0.7.0. That's a small PR aiming to fix it.

2022-08-02 13:27 UTC, MksmOrlov approved these changes

2022-08-09 08:53 UTC, MksmOrlov requested changes

2022-08-09 08:53 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/logic/LogicExpression.cpp
> +    SC_LOG_DEBUG(context->HelperGetSystemIdtf(node); + " is a template");
```suggestion
    SC_LOG_DEBUG(context->HelperGetSystemIdtf(node) + " is a template");
```

2022-08-09 08:53 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/logic/LogicExpression.cpp
> +    SC_LOG_DEBUG(context->HelperGetSystemIdtf(node); + " is a template");
And so on

2022-08-10 06:22 UTC, MksmOrlov commented
Fixed in https://github.com/ostis-apps/ostis-inference/pull/28

2022-08-18 17:56 UTC, FallenChromium commented
Closed in favor of #28

2022-08-18 17:56 UTC, closed without merging