docs: add scn-tex documentation, add README
ostis-apps/ostis-inference pull request #32
Opened 2022-10-13 16:09 UTC by MksmOrlov

2022-10-14 18:49 UTC, AlexandrZagorskiy requested changes

2022-10-14 18:49 UTC, AlexandrZagorskiy commented on docs/SCL_machine.tex
> +                        или наоборот: значением \_x sc-eузел argument\_2, а значением \_y -- argument\_1.}
```suggestion
                        \scntext{пояснение}{В данном примере значением переменной \_x в шаблоне цели может быть sc-узел argument\_1, тогда значением \_y будет argument\_2.
                        Также значением переменной \_x может быть sc-узел argument\_2, а значением \_y -- argument\_1.}
```

2022-10-14 18:49 UTC, AlexandrZagorskiy commented on docs/SCL_machine.tex
> +                        или наоборот: значением \_x sc-eузел argument\_2, а значением \_y -- argument\_1.}
What is the basis of the choice? How developer should understand and control it?

2022-10-14 18:49 UTC, AlexandrZagorskiy commented on docs/SCL_machine.tex
> +                \scnfileitem{Построение вектора очереди правил на основе множества правил. Цикл по всем правилам и по не достигнута цель;}
```suggestion
                \scnfileitem{Построение вектора очереди правил на основе множества правил. Цикл по всем правилам пока не достигнута цель;}
```

2022-10-14 19:00 UTC, MksmOrlov commented on docs/SCL_machine.tex
> +                        или наоборот: значением \_x sc-eузел argument\_2, а значением \_y -- argument\_1.}
Random. Without control

2022-10-17 14:28 UTC, AlexandrZagorskiy approved these changes

2022-10-18 11:19 UTC, SHtress approved these changes

2022-10-18 11:19 UTC, SHtress commented on docs/scl-machine.tex
> +    например, Modes ponens и другие правила, в процессе логического вывода.}
```suggestion
    например, Modus ponens и другие правила, в процессе логического вывода.}
```

2022-10-18 11:34 UTC, merged